version: 0.2

phases:
  pre_build:
    commands:
      - echo npm install
      - npm install
      - npm install react react-dom
  build:
    commands:
      - echo npm start
      - npm start
  post_build:
    commands:
      - echo Build completed on `date`